version: '3.7'

networks:
  network:
  testing:

volumes:
  downloads-test:
  pgdata:
  tmp:
  opdata:
  bundle:
  npm:
  pgdata-test:
  tmp-test:
  fedata-test:

x-op-restart-policy: &restart_policy
  restart: unless-stopped

x-op-build: &build
  context: .
  dockerfile: ./docker/dev/backend/Dockerfile
  args:
    DEV_UID: 1000
    DEV_GID: 1001

x-op-image: &image
  image: otechproject:1.0

x-op-frontend-build: &frontend-build
  context: .
  dockerfile: ./docker/dev/frontend/Dockerfile
  args:
    DEV_UID: 1000
    DEV_GID: 1001

services:
  backend:
    build:
      <<: *build
      target: develop
    image: otechproject:1.0
    restart: unless-stopped
    environment:
      LOCAL_DEV_CHECK: ${LOCAL_DEV_CHECK:-}
      RAILS_ENV: development
      OPENPROJECT_CACHE__MEMCACHE__SERVER: cache:11211
      OPENPROJECT_RAILS__CACHE__STORE: file_store
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}
      DATABASE_URL: postgresql://${DB_USERNAME:-otechproject}:${DB_PASSWORD:-Simon@1234}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_DATABASE:-otechproject_dev}
      OPENPROJECT_EDITION: ${OPENPROJECT_EDITION:-standard}
      OPENPROJECT_WEB_MAX__THREADS: 1
      OPENPROJECT_WEB_MIN__THREADS: 1
      OPENPROJECT_WEB_WORKERS: 0
    volumes:
      - ".:/root/otech/v9/openproject"
      - "opdata:/var/openproject/assets"
      - "bundle:/usr/local/bundle"
      - "tmp:/root/otech/v9/openproject/tmp"
    networks:
      - network
    depends_on:
      - db
      - cache

  worker:
    build:
      <<: *build
      target: develop
    image: otechproject:1.0
    restart: unless-stopped
    command: bundle exec good_job start
    environment:
      RAILS_ENV: development
      OPENPROJECT_CACHE__MEMCACHE__SERVER: cache:11211
      OPENPROJECT_RAILS__CACHE__STORE: file_store
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}
      DATABASE_URL: postgresql://${DB_USERNAME:-postgres}:${DB_PASSWORD:-postgres}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_DATABASE:-openproject}
      OPENPROJECT_EDITION: ${OPENPROJECT_EDITION:-standard}
      OPENPROJECT_WEB_MAX__THREADS: 1
      OPENPROJECT_WEB_MIN__THREADS: 1
      OPENPROJECT_WEB_WORKERS: 0
    volumes:
      - ".:/home/dev/openproject"
      - "opdata:/var/openproject/assets"
      - "bundle:/usr/local/bundle"
      - "tmp:/root/otech/v9/openproject/tmp"
    networks:
      - network
    depends_on:
      - db
      - cache

  frontend:
    build:
      <<: *frontend-build
    image: otechproject:1.0
    restart: unless-stopped
    command: "node --max_old_space_size=8096 ./node_modules/@angular/cli/bin/ng serve --host 0.0.0.0 --public-host ${OPENPROJECT_DEV_URL}"
    volumes:
      - ".:/root/otech/v9/openproject"
      - "${CKEDITOR_BUILD_DIR:-./frontend/src/vendor/ckeditor/}:/root/otech/v9/openproject/frontend/src/vendor/ckeditor/"
    environment:
      PROXY_HOSTNAME: backend
    networks:
      - network
    depends_on:
      - backend

  db:
    image: postgres:13
    restart: unless-stopped
    stop_grace_period: "3s"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-otechproject}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Simon@1234}
      POSTGRES_DB: ${DB_DATABASE:-otechproject_dev}
    networks:
      - network

  cache:
    image: memcached
    restart: unless-stopped
    networks:
      - network

  db-test:
    image: postgres:13
    restart: unless-stopped
    stop_grace_period: "3s"
    volumes:
      - "pgdata-test:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: openproject
      POSTGRES_USER: openproject
      POSTGRES_PASSWORD: openproject
    networks:
      - testing

  frontend-test:
    build:
      <<: *frontend-build
    restart: unless-stopped
    command: "npm run serve:test"
    volumes:
      - ".:/root/otech/v9/openproject"
      - "fedata-test:/root/otech/v9/openproject/public/assets/frontend"
    environment:
      PROXY_HOSTNAME: backend-test
      CHROME_BIN: chromium
    networks:
      - testing

  backend-test:
    build:
      <<: *build
      target: test
    restart: unless-stopped
    command: setup-tests
    hostname: backend-test
    networks:
      - testing
    depends_on:
      - db-test
      - selenium-hub
      - frontend-test
      - cuprite-chrome
    environment:
      RAILS_ENV: test
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}
      DATABASE_URL: postgresql://openproject:openproject@db-test/openproject
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      SELENIUM_GRID_URL: http://selenium-hub:4444/wd/hub
      CHROME_URL: http://cuprite-chrome:3333
      CAPYBARA_SERVER_PORT: 3000
      CAPYBARA_DYNAMIC_BIND_IP: 1
      CAPYBARA_APP_HOSTNAME: backend-test
      OPENPROJECT_EMAIL__DELIVERY__METHOD: test
      OPENPROJECT_CLI_PROXY: http://frontend-test:4200
      OPENPROJECT_TESTING_NO_HEADLESS: "true"
      OPENPROJECT_TESTING_AUTO_DEVTOOLS: "true"
    volumes:
      - ".:/home/dev/openproject"
      - "fedata-test:/root/otech/v9/openproject/public/assets/frontend"
      - "opdata:/var/openproject/assets"
      - "bundle:/usr/local/bundle"
      - "tmp-test:/root/otech/v9/openproject/tmp"
      - "./tmp/capybara:/root/otech/v9/openproject/tmp/capybara"

  selenium-hub:
    image: selenium/hub:4
    container_name: selenium-hub
    hostname: selenium-hub
    environment:
      GRID_MAX_SESSION: ${CI_JOBS:-4}
    depends_on:
      - chrome
      - firefox
      - opera
    networks:
      - testing

  chrome:
    image: selenium/node-chrome:4
    restart: unless-stopped
    volumes:
      - /dev/shm:/dev/shm
      - "downloads-test:/home/seluser/Downloads"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
      NODE_MAX_INSTANCES: ${CI_JOBS:-4}
      NODE_MAX_SESSION: ${CI_JOBS:-4}
    networks:
      - testing

  firefox:
    image: selenium/node-firefox:4
    restart: unless-stopped
    volumes:
      - /dev/shm:/dev/shm
      - "downloads-test:/home/seluser/Downloads"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
      NODE_MAX_INSTANCES: ${CI_JOBS:-4}
      NODE_MAX_SESSION: ${CI_JOBS:-4}
    networks:
      - testing

  opera:
    image: selenium/node-opera:4
    restart: unless-stopped
    volumes:
      - /dev/shm:/dev/shm
      - "downloads-test:/home/seluser/Downloads"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
      NODE_MAX_INSTANCES: ${CI_JOBS:-4}
      NODE_MAX_SESSION: ${CI_JOBS:-4}
    networks:
      - testing

  cuprite-chrome:
    image: browserless/chrome:latest
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      CONNECTION_TIMEOUT: 600000
    networks:
      - testing
